// Generated by CoffeeScript 1.3.3
(function() {

  window.GhostsAndMonstersGame = (function() {
    var PIXELS_PER_METER, forceMultiplier, frameRate, gravityX, gravityY;

    PIXELS_PER_METER = 20;

    gravityX = 0;

    gravityY = 10;

    frameRate = 60;

    forceMultiplier = 5;

    $(document).ready(function() {
      var canvas, debugCanvas, statsCanvas;
      canvas = document.getElementById('easelCanvas');
      debugCanvas = document.getElementById('debugCanvas');
      statsCanvas = document.getElementById('stats');
      return new GhostsAndMonstersGame(canvas, debugCanvas, statsCanvas);
    });

    GhostsAndMonstersGame.prototype.reset = function() {
      return alert(window.innerWidth);
    };

    function GhostsAndMonstersGame(canvas, debugCanvas, statsCanvas) {
      var g;
      g = new Graphics();
      this.world = new EaselBoxWorld(this, frameRate, canvas, debugCanvas, gravityX, gravityY, PIXELS_PER_METER);
      this.world.addLandscape({
        width: canvas.width,
        height: canvas.height,
        iterations: 8,
        smoothness: 0.05,
        vertical_offset: canvas.height - 150,
        type: 'static'
      });
      this.monkey1 = this.world.addMonkey({
        imgSrc: '/img/gorilla_left.png',
        scaleX: 0.3,
        scaleY: 0.3,
        size_head: 15,
        size_torso: 20,
        size_lowerbody: 22,
        density: 2,
        friction: 0.8,
        restitution: 0.3,
        xPixels: 25,
        yPixels: 300,
        regX: 60,
        regY: 190
      });
      this.monkey2 = this.world.addMonkey({
        imgSrc: '/img/gorilla_right.png',
        scaleX: 0.3,
        scaleY: 0.3,
        size_head: 15,
        size_torso: 20,
        size_lowerbody: 22,
        density: 2,
        friction: 0.8,
        restitution: 0.3,
        xPixels: 745,
        yPixels: 300,
        regX: 230,
        regY: 190
      });
      this.arrow = this.world.addArrow({
        xPixels: 100,
        yPixels: 100,
        /*
              The arrow is sketched below. Lettered points are the ones actually drawn in alphabetical order(i.e. A-F)
              The X-es are shown for illustration only. 
              Coordinates are A = (x1,y1), B = (x2,y2) and so on. The last point is F = (x6,y6) 
                                                         E
                                                         D    X
                                               X                 X
                                     X                              X
                           X                                           X    
               A                                                          F    
                           X                                           X    
                                     X                              X           
                                               X                 X  
                                                         B   X
                                                         C
        */

        shape_coordinates: [100, 100, 170, 110, 170, 115, 170, 90, 170, 85, 190, 100],
        rotation: 45
      });
      this.stats = new Stats();
      statsCanvas.appendChild(this.stats.domElement);
    }

    GhostsAndMonstersGame.prototype.tick = function() {
      return this.stats.update();
    };

    return GhostsAndMonstersGame;

  })();

}).call(this);
